feat: 단일 문제 조회, problemMemo 내용 수정 기능 구현
Alchive-grad-work/backend pull request #35
Opened 2024-04-13 10:11 UTC by omgomg333

## Summary

제목의 두 기능을 구현했습니다.

## Description

- ProblemController.java 메서드 추가
- ProblemService.java 메서드 추가
- ProblemRepository 추가

## Screenshot

![image](https://github.com/Alchive-grad-work/backend/assets/133757508/649f487f-04e0-417c-8681-38ddb59565f1)
단일 문제 조회 성공공

![image](https://github.com/Alchive-grad-work/backend/assets/133757508/18940734-4741-4b60-83c5-a379457daa6b)
problemMemo 내용 수정 성공

## Test Checklist

- [ ] 체크리스트

2024-04-13 10:42 UTC, dlwhsk0 reviewed
리뷰 한 번 쓰면 삭제가 안되는군요 아래에 다시 넣었어용

2024-04-13 10:42 UTC, dlwhsk0 requested changes
단일 문제 조회
- ResponseBody에 내용이 더 들어가야합니다 알고리즘이랑 Problem 도메인에 있는 칼럼 다 넣으면 될 것 같아요
- 단일 문제 조회만의 DTO를 만들어서 하는게 좋을 것 같습니다

메모 수정
- memo가 들어갈 때 ""에 감싸져서 들어가고 있네용
<img width="426" alt="스크린샷 2024-04-13 오후 7 37 23" src="https://github.com/Alchive-grad-work/backend/assets/94193594/4b72b43a-9bb7-4463-840c-3bc861522cec">
문제 작성자 아이디랑 유저 아이디가 같지 않을 때 에러 메시지가 그냥 문제를 불러오는걸 실패했다고 뜨네요 이 부분에 대한 에러 처리를 따로 만들어도 좋을듯!

@RequestParam에 대해 검색해보세요 @PathVariable 랑 @RequestBody 안에서 해결하려고 해서 엔드포인트를 변경하는 방식으로 가는 것 같네용

2024-04-19 07:13 UTC, dlwhsk0 approved these changes

2024-04-19 11:57 UTC, nahowo approved these changes
테스트 잘 작동합니다!! 수고했어요~!

2024-04-20 06:12 UTC, merged